""" Scripts for running/checking PlasMerge and PlasEval """

import os
import sys
import argparse
import csv
import subprocess
from itertools import product
import tarfile
import shutil

""" Plasmid binning methods """
# Names of binning methods used in experiments
GT = "ground_truth"
GP = "gplascc"
MOB = "mobrecon"
PBF = "plasbinflow"
BINNING = [PBF, GP, MOB, GT]
# Map of binning methods names used in experiments
# to names used in PlasMerge and in the data file column names
BINNING_MAP = {PBF: "pbf", GP: "gp", GT: "gt", MOB: "mob"}

""" Classfication methods """
# Names of classification methods used in experiments
PLSC = "plasclass"
PLSG = "plasgraph2"
MLP = "mlplasmids"
RFP = "rfplasmid"
CLASSIFICATION = [PLSC, PLSG, MLP, RFP]
# Map of classification methods names used in experiments
# to names used in PlasMerge and in the data file column names
CLASSIFICATION_MAP = {PLSC: "plcl", PLSG: "plgr", MLP: "mlpl", RFP: "rfpl"}

""" Data access keys """
SAMPLE = "species_sample"
ASSEMBLER = "assembler"
GFA = "gfa_100_gz"
GC_PROBS = "gc_probs"
GC_BINS="gc_bins_file"
OUT_DIR="out_dir"
PLASMERGE="plasmerge"
PLASEVAL="plaseval"
# Merged status
MERGED_KEY="merged"
MERGED="merged"
UNMERGED="unmerged"
MERGED_STATUS = [MERGED,UNMERGED]
# Key to the field recordig a binning method in the main data dictionary
BINNING_KEY = "binning"
# Key to the field recordig a classification method in the main data dictionary
CLASS_KEY = "classification"
# PlasMerge meging scores file
SCORES="merging_scores"
# PlasEval alpha parameter
ALPHA_KEY="alpha"
# Key for input file error
INPUT_FILE="input"

""" PlasEval/PlasEval files suffixes """
SCORES_OUT="merging_scores.tsv"
EVAL_CMD="eval"
COMP_CMD="comp"
EVAL_OUT=f"{EVAL_CMD}.out"
COMP_OUT=f"{COMP_CMD}.out"
COMP_LOG=f"{COMP_CMD}.log"

""" Plasval default values """
MIN_LEN=100
MAX_CALLS=1000000
ALPHA=0.5

""" Generic functions """

class MissingFileError(Exception):
    """ Excepion raised when a file is missing """
    pass

class EmptyFileError(Exception):
    """ Excepion raised when a file is empty """
    pass

def _check_files(in_files, in_msg="", exit_if_pbm=True):
    """ Checking if a list of files is present and not empty
    Input:
    - in_files: list(str) list of file paths
    - in_msg: (str) message added to prints when errors
    - exit_if_pbm: (bool) if Tue, exist with 1 as son as a file is missing or empty
    Output: (if no exit)
    - bool: True if all files are present and none is empty
    Actions:
    prints a message for all checked files, with prefix #ERROR if file issing or empty
    """
    outcome = True
    for in_file in in_files:
        try:
            if not os.path.exists(in_file):
                raise MissingFileError(f"file {in_file} is missing")
            elif os.path.getsize(in_file) == 0:
                raise EmptyFileError(f"file {in_file} is empty")
            else:
                print(f"LOG: {in_msg} file {in_file} OK")
        except (MissingFileError, EmptyFileError) as e:
            print(f"ERROR: {in_msg} {e.args[0]}")
            if exit_if_pbm:
                sys.exit(1)
            else:
                outcome = False
    return outcome

def _sample_dir(sample_id, assembler, out_dir):
    return os.path.join(
        out_dir, f"{sample_id}_{assembler}"
    )

def _bins_file_path(
        sample_id, assembler,
        binning, classification,
        out_dir, merged, method
):
    """ Return the path of a generated plasmid bins file
    A bins file is either initial (present in the data file) or has been generated by a
    method (either PlasMege for merging) or PlasEval (conversion of a PlasMerge file)
    Input:
    - sample_id: (str) sample processed
    - assembler: (str) assembler used
    - binning: (str in BINNING) binning method used to generate the initial bins file
    - classifcation: (str in CLASSIFICATION) classification method used (ibid)
    - out_dir: (str) directory where to look for the file
    - merged: (str in MERGED): merged tatus of the bins
    - method: (str in [PLASMERGE,PLASEVAL]: method used to generate the processed file
    Output:
    - str: bins file path
    """
    return os.path.join(
        out_dir,
        f"{sample_id}_{assembler}.{binning}_{classification}.{method}.{merged}.tsv"
    )

def _merging_scores_file_path(
        sample_id, assembler,
        binning, classification,
        out_dir
):
    """ Returns the path to a bins meging score file generated by PlasMerge
    Input: see _bins_file_path
    - sample_id: (str) sample processed
    - assembler: (str) assembler used
    - binning: (str in BINNING) binning method used to generate the initial bins file
    - classifcation: (str in CLASSIFICATION) classification method used (ibid)
    - out_dir: (str) directory where to look for the file
    Output:
    - str: bins file path
    """
    return os.path.join(
        out_dir,
        f"{sample_id}_{assembler}.{binning}_{classification}.{PLASMERGE}.{SCORES_OUT}"
    )

def _plaseval_file_path(
        sample_id, assembler,
        binning, classification,
        out_dir,
        merged, alpha, suffix
):
    """ Returns the path of a file generated by PlasEval
    - sample_id: (str) sample processed
    - assembler: (str) assembler used
    - binning: (str in BINNING) binning method used to generate the initial bins file
    - classifcation: (str in CLASSIFICATION) classification method used (ibid)
    - out_dir: (str) directory where to look for the file
    - merged: (str in MERGED): merged tatus of the bins
    - alpha: (str either "" or  str(float)) alpha value used for PlasEval comp
      if "" => eval: the precision/recall/F1 file path is returned
    - suffix: (str in [EVAL_OUT,COMP_OUT,COMP_LOG]) returned file suffix
    Output:
    - str: PlasEval file path
    Use:
    To return the "eval" file: set alpha to "" and suffix=EVAL_OUT
    To return the "comp" log file, set alpha to its float value and suffix=COMP_LOG
    To return the "comp" out file, set alpha to its float value and suffix=COMP_OUT
    """
    if len(alpha) > 0:
        suffix2 = f"_{alpha}"
    else:
        suffix2 = ""
    return os.path.join(
        out_dir,
        f"{sample_id}_{assembler}.{binning}_{classification}.{merged}.{suffix}{suffix2}"
    )

""" Reading data
All data about processed samples are stored in a dictionary generated by _read_samples_data
index 1: sample index
index 2: sample information
SAMPLE: sample id
ASSEMBLER: assembler
GFA: gzipped GFA file
GC_PROBS: contigs GC pobabilities file
c in CLASSIFICATION: path to classification method c results file, in PlasBin-flow format

In all key below, b,c in BINNING x CLASSIFICATION
(b,c): initial plasmid bins file (in PlasEval format) obtained
       with binning (resp. classification) method b (resp c).
OUT_DIR: directory whee all results files for the sample are stored
(PLASMERGE,b,c,SCORES): merging scores file generated by PlasMerge for combination (b,c)
(PLASMERGE,b,c,UNMERGED): input (unmerged bins) file to PlasMerge for combination (b,c)
(PLASMERGE,b,c,MERGED): output (megred bis) file to PlasMerge for combination (b,c)
Both files above are in PlasMerge format.
(PLASEVAL,b,c,UNMERGED): input (unmerged bins) file to PlasMerge for combination (b,c)
(PLASEVAL,b,c,MERGED): output (megred bis) file to PlasMerge for combination (b,c)
Both files above are in PlasEval format, and b,c,m in BINNING x CLASSIFICATION x MERGED_STATUS
(PLASEVAL,b,c,m,EVAL_OUT): eval file generated by PlasEval for m bins and combination (b,c)
(PLASEVAL,b,c,m,COMP_LOG,a): comp log file generated by PlasEval for m bins and combination (b,c) and alpha=a
(PLASEVAL,b,c,m,COMP_OUT): comp out file generated by PlasEval for m bins and combination (b,c) and alpha=a

Keys below are used only to read a rerun data file recoding samples for which a PlasMerge experiment
did not succeed; only such files have the additional columns corresponding to these keys
BINNING_KEY in BINNING: binning method 
CLASSIFICATION_KEY in CLASSIFICATION: classification method

Keys below are used only to read a rerun data file recoding samples for which a PlasEval experiment
did not succeed; only such files have the additional columns corresponding to these keys
BINNING_KEY in BINNING: binning method 
CLASSIFICATION_KEY in CLASSIFICATION: classification method
MERGED_KEY: merged status
ALPHA_KEY: alpha value (or INPUT_FILE if an input file is missing or EVAL_CMD if eval failed)(
"""

def _read_samples_data(
        in_data_file, in_sample_idx,
        in_alpha,
        out_dir,
        rerun_plasmerge=False, rerun_plaseval=False
):
    """ Reading the samples data file and creating a dictionary recording all possible files paths
    Input:
    - in_data_file: (str) path to the samples data CSV fle
    - in_sample_idx: list(int) index in the file of the samples to read (1-base)
    - in_alpha: list(str): list of alpha values (considerign several values is used to check PlasEval results)
    - out_dir: (str) directory where are stored all experimetal results (one sub-directory per sample)
    - rerun_plasmerge: (bool) if True, read additional columns recording combinations for failed PlasMerge experiments
    - rerun_plaseval: (bool) ibid but for PlasEval
    Note: rerun_plasmerge and rerun_plaseval are used to read data for failed experiments to be redone, not the initial
    file
    Output:
    - dict(dict(k: str): dictionary used to access all informations about one or several samples
    index 1: samples
    index 2: keys to access sample information, see description above
    """
    _check_files([in_data_file])
    all_samples_data_dict = {}
    with open(in_data_file, newline='') as csvfile:
        data_lines = list(csv.DictReader(csvfile))        
        for sample_idx in in_sample_idx:
            sample_data = data_lines[sample_idx-1]
            sample_data_dict = {}
            # Reading data in CSV samples file
            sample_data_dict[SAMPLE] = sample_data[SAMPLE]
            sample_data_dict[ASSEMBLER] = sample_data[ASSEMBLER]
            sample_data_dict[GFA] = sample_data[GFA]
            sample_data_dict[GC_PROBS] = sample_data[GC_PROBS]
            for classification in CLASSIFICATION:
                sample_data_dict[classification] = sample_data[
                    f"input_pbf_{CLASSIFICATION_MAP[classification]}"
                ]
            for (binning,classification) in product(BINNING, CLASSIFICATION):
                if binning == MOB: sample_data_key = "mob_bins"
                elif binning == GT: sample_data_key = "gt_bins"
                else: sample_data_key = f"{BINNING_MAP[binning]}_{CLASSIFICATION_MAP[classification]}_bins"
                sample_data_dict[(binning,classification)] = sample_data[sample_data_key]            
            # Output directory
            sample_data_dict[OUT_DIR] = _sample_dir(
                sample_data_dict[SAMPLE], sample_data_dict[ASSEMBLER], out_dir
            )
            # PlasMerge files in PlasMerge format
            for (binning,classification) in product(BINNING, CLASSIFICATION):
                # Merging scores file
                key = (PLASMERGE,binning,classification,SCORES)
                sample_data_dict[key] =  _merging_scores_file_path(
                    sample_data_dict[SAMPLE], sample_data_dict[ASSEMBLER],
                    binning, classification, sample_data_dict[OUT_DIR]
                )
                # Bins files
                for merged in MERGED_STATUS:
                    key = (PLASMERGE,binning,classification,merged)
                    sample_data_dict[key] = _bins_file_path(
                        sample_data_dict[SAMPLE], sample_data_dict[ASSEMBLER],
                        binning, classification, sample_data_dict[OUT_DIR],
                        merged, PLASMERGE
                    )
            # PlasEval files in PlasEval format
            for (binning,classification,merged) in product(BINNING,CLASSIFICATION,MERGED_STATUS):
                key = (PLASEVAL,binning,classification,merged)
                # Bins files
                sample_data_dict[key] = _bins_file_path(
                sample_data_dict[SAMPLE], sample_data_dict[ASSEMBLER],
                    binning, classification, sample_data_dict[OUT_DIR],
                    merged, PLASEVAL
                )
                # Eval files
                key = (PLASEVAL,binning,classification,merged,EVAL_OUT)
                sample_data_dict[key] = _plaseval_file_path(
                    sample_data_dict[SAMPLE], sample_data_dict[ASSEMBLER],
                    binning, classification, sample_data_dict[OUT_DIR],
                    merged, "", EVAL_OUT
                )
                if len(in_alpha) > 0:
                    # Comp files
                    for (alpha,comp_suffix) in product(in_alpha,[COMP_OUT,COMP_LOG]):
                        key = (PLASEVAL,binning,classification,merged,comp_suffix,float(alpha))
                        sample_data_dict[key] = _plaseval_file_path(
                            sample_data_dict[SAMPLE], sample_data_dict[ASSEMBLER],
                            binning, classification, sample_data_dict[OUT_DIR],
                            merged, alpha, comp_suffix
                        )
            # Re-run information: classification, binning,alpha,merged status 
            if rerun_plasmerge or rerun_plaseval:
                sample_data_dict[BINNING_KEY] = sample_data[BINNING_KEY]
                sample_data_dict[CLASS_KEY] = sample_data[CLASS_KEY]
            if rerun_plaseval:
                sample_data_dict[ALPHA_KEY] = sample_data[ALPHA_KEY]
                sample_data_dict[MERGED_KEY] = sample_data[MERGED_KEY]
            all_samples_data_dict[sample_idx] = sample_data_dict
    return all_samples_data_dict

def _read_binning_classification(sample_data_dict, args):
    """ Returns a binning ethod and a classification method for a sample
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - (str,str): name of a binning method and a classification method
    """
    if args.rerun:
        binning = sample_data_dict[BINNING_KEY]
        classification = sample_data_dict[CLASS_KEY]
    else:
        binning = args.binning
        classification = args.classification
    return binning,classification

def _read_merged_status(sample_data_dict, args):
    """ Returns a merged status
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - (str) in MERGED_STATUS
    """
    if args.rerun:
        merged = sample_data_dict[MERGED_KEY]
    else:
        merged = args.merged_status
    return merged

def _read_alpha(sample_data_dict, args):
    """ Returns a alpha value used in a PlasEval experiment
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - (str): alpha value
    """    
    if args.rerun:
        alpha = sample_data_dict[ALPHA_KEY]
    else:
        alpha = str(args.alpha)
    return alpha

def _prefix(sample_data_dict, binning, classification):
    """ Reurns the prefix of a file name
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - binning: (str in BINNING) binning method
    - classification: (str in CLASSIFICATION) classification method
    Output:
    - (str): file name prefix
    """
    return f"{sample_data_dict[SAMPLE]}_{sample_data_dict[ASSEMBLER]}.{binning}_{classification}"

""" PlasMerge functions """

def _create_convert_bins_to_plasmerge_command(sample_data_dict, args):
    """ Create the command to convert a bins file from PlasEval format to PlasMerge format
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - list(str),str,str:
    command
    path to input file (PlasEval bins)
    path to output file (PlasMerge bins)
    """
    binning,classification = _read_binning_classification(sample_data_dict, args)
    convert_cmd = [
        f"python{args.python_version}",
        os.path.join(args.plasmerge_path, "convert_utils.py"),
        sample_data_dict[(binning,classification)],
        sample_data_dict[(PLASMERGE,binning,classification,UNMERGED)],
        "gt"
    ]
    in_file = sample_data_dict[(binning,classification)]
    out_file = sample_data_dict[(PLASMERGE,binning,classification,UNMERGED)]
    return convert_cmd,in_file,out_file
    
def convert_bins_to_plasmerge(sample_data_dict, args):
    """ Run command to convert a bins file fom PlasEval format to PlasMerge format
     Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output: None   
    """
    convert_cmd,in_file,out_file = _create_convert_bins_to_plasmerge_command(sample_data_dict, args)
    # Checking input files
    if os.path.exists(out_file):
        print(f"WARNING: Converting unmerged bins - file {out_file} does exist already")
        return
    _check_files([in_file], in_msg="PlasMerge converting unmerged bins -")
    try:        
        convert_cmd_str = " ".join(convert_cmd)
        print(f"LOG: Converting bins - [{convert_cmd_str}]")
        result = subprocess.run(convert_cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: PlasMerge converting bins - [{convert_cmd_str}] failed with return code {e.returncode}")
        sys.stderr.write(e.stderr)
        sys.exit(1)
    _check_files([out_file], in_msg="PlasMerge converting unmerged bins -")

def _gurobi_dir(sample_data_dict, args):
    """ Returns the path of directory containing Gurobi results
     Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - str: directory path
    """
    binning,classification = _read_binning_classification(sample_data_dict, args)
    return os.path.join(
        sample_data_dict[OUT_DIR],
        _prefix(sample_data_dict, binning, classification)
    )

def _create_plasmerge_command(sample_data_dict, args):
    """ Create the command to run PlasMerge on a sample
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - list(str),list(str),list(str):
    command
    list of paths to input files (GFA file, classification scores file,unmeged bins file
    list of paths to output files (merging scoes file, merged bins file)
    """
    binning,classification = _read_binning_classification(sample_data_dict, args)
    gurobi_out_dir = _gurobi_dir(sample_data_dict, args)
    os.makedirs(gurobi_out_dir, exist_ok=True)
    # Command
    plasmerge_cmd = [
        f"python{args.python_version}",
        os.path.join(args.plasmerge_path, "plasmerge.py"),
        "-s", sample_data_dict[SAMPLE],
        "-t", sample_data_dict[ASSEMBLER].lower(),
        "-r", BINNING_MAP[binning],
        "-a", sample_data_dict[GFA],
        "-p", sample_data_dict[classification],
        "-b", sample_data_dict[(PLASMERGE,binning,classification,UNMERGED)],
        "-l",
        "-d", gurobi_out_dir,
        "-os", sample_data_dict[(PLASMERGE,binning,classification,SCORES)],
        "-om", sample_data_dict[(PLASMERGE,binning,classification,MERGED)],
        "-g", args.gc_bins_file
    ]
    in_files = [
        sample_data_dict[GFA],
        sample_data_dict[classification],
        sample_data_dict[(PLASMERGE,binning,classification,UNMERGED)],
        args.gc_bins_file
    ]
    out_files = [
        sample_data_dict[(PLASMERGE,binning,classification,MERGED)],
        sample_data_dict[(PLASMERGE,binning,classification,SCORES)]
    ]
    return plasmerge_cmd,in_files,out_files

def _archive_gurobi_dir(sample_data_dict, args):
    """ Create an archive of Gurobi results and delete directory
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output: None
    """
    gurobi_out_dir = _gurobi_dir(sample_data_dict, args)
    gurobi_tarfile = f"{gurobi_out_dir}.tar.gz"
    with tarfile.open(gurobi_tarfile, "w:gz") as tar:
        tar.add(gurobi_out_dir, arcname=os.path.basename(gurobi_out_dir))
    shutil.rmtree(gurobi_out_dir)

def run_plasmerge(args):
    """ Run PlasMerge on a single sample for a combination (binning,classification)
    Input:
    - args: (argparse object) argument for the plasmerge command
    Output: None
    """
    # Reading data for the sample to process
    sample_data_dict = _read_samples_data(
        args.data_file, [args.sample_idx], [], args.output_dir, rerun_plasmerge=args.rerun
    )[args.sample_idx]
    # Converting unmerged bins into PlasMerge format
    os.makedirs(sample_data_dict[OUT_DIR], exist_ok=True)
    convert_bins_to_plasmerge(sample_data_dict, args)    
    # Running PlasMerge
    plasmerge_cmd,in_files,out_files = _create_plasmerge_command(sample_data_dict, args)
    _check_files(in_files, in_msg="Running PlasMerge -")
    try:
        plasmerge_cmd_str = " ".join(plasmerge_cmd)
        print(f"LOG: Running PlasMerge - [{plasmerge_cmd_str}]")
        result = subprocess.run(plasmerge_cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Running PlasMerge - [{plasmerge_cmd_str}] failed with return code {e.returncode}")
        print(f"Error output: {e.stderr}")
        sys.exit(1)
    _check_files(out_files, in_msg="Running PlasMerge -")
    _archive_gurobi_dir(sample_data_dict, args)

def check_plasmerge(args):
    """ Check PlasMerge input/output on a set of samples for all combinations (binning,classification)
    Input:
    - args: (argparse object) argument for the CHECK_PLASMERGE command
    Output: None
    Creates a CSV file with all failed experiments, recording the combination (binning,classification)
    """
    samples_id_range = range(1,args.nb_samples+1)
    all_samples_data_dict = _read_samples_data(
        args.data_file, samples_id_range, [], args.output_dir
    )
    failed_experiments = []
    for (sample_idx,binning,classification) in product(
            samples_id_range,args.binning.split(","),args.classification.split(",")
    ):
        sample_data_dict = all_samples_data_dict[sample_idx]
        files_to_check = [
            sample_data_dict[GFA],
            sample_data_dict[(binning,classification)],
            sample_data_dict[classification],
            sample_data_dict[(PLASMERGE,binning,classification,UNMERGED)],
            sample_data_dict[(PLASMERGE,binning,classification,MERGED)],
            sample_data_dict[(PLASMERGE,binning,classification,SCORES)]
        ]
        correct = _check_files(
            files_to_check,
            in_msg=_prefix(sample_data_dict, binning, classification),
            exit_if_pbm=False
        )
        if not correct:
            failed_experiments.append((sample_idx,binning,classification))
    with open(args.data_file) as in_file, open(args.output_file,"w") as out_file:
        in_lines = in_file.readlines()
        out_file.write(f"{in_lines[0].rstrip()},binning,classification")
        for (sample_idx,binning,classification) in failed_experiments:
            out_file.write(f"\n{in_lines[sample_idx].rstrip()},{binning},{classification}")
            
""" PlasEval functions """

def _create_convert_bins_to_plaseval_command(sample_data_dict, args):
    """ Create the command to convert a bins file from PlasMerge format to PlasEval format, discarding within-bin repeats
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - list(str),list(str),str:
    command
    path to input files (GFA file, PlasMerge bins)
    path to output file (PlasEval bins)
    """
    binning,classification = _read_binning_classification(sample_data_dict, args)
    merged_status = _read_merged_status(sample_data_dict, args)
    convert_cmd = [
        f"python{args.python_version}",
        os.path.join(args.plasmerge_path, "convert_utils.py"),
        sample_data_dict[(PLASMERGE,binning,classification,merged_status)],
        sample_data_dict[(PLASEVAL,binning,classification,merged_status)],
        "to_plaseval_norep",
        sample_data_dict[GFA]
    ]
    in_files = [
        sample_data_dict[GFA],
        sample_data_dict[(PLASMERGE,binning,classification,merged_status)],
    ]
    out_file = sample_data_dict[(PLASEVAL,binning,classification,merged_status)]
    return convert_cmd,in_files,out_file

def convert_bins_to_plaseval(sample_data_dict, args):
    """ Run command to convert a bins file fom PlasMerge format to PlasEval format
     Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output: None   
    """
    convert_cmd,in_files,out_file = _create_convert_bins_to_plaseval_command(
        sample_data_dict, args
    )
    if os.path.exists(out_file):
        print(f"WARNING: Converting bins - file {out_file} does exist already")
        return
    _check_files(in_files, in_msg="PlasEval converting PlasMerge bins -")
    try:       
        convert_cmd_str = " ".join(convert_cmd)
        print(f"LOG: Converting bins - [{convert_cmd_str}]")
        result = subprocess.run(convert_cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: PlasEval converting bins - [{convert_cmd_str}] failed with return code {e.returncode}")
        sys.stderr.write(e.stderr)
        sys.exit(1)
    _check_files([out_file], in_msg="PlasEval converting PlasMerge bins -")

def _create_plaseval_eval_command(sample_data_dict, args):
    """ Create the command to run PlasEval in eval mode
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - list(str),list(str),str:
    command
    path to input files (ground truth bins, predicted bins)
    path to output file (PlasEval eval sats file)
    """
    binning,classification = _read_binning_classification(sample_data_dict, args)
    merged_status = _read_merged_status(sample_data_dict, args)    
    plaseval_cmd = [
        f"python{args.python_version}",
        os.path.join(args.plaseval_path, "plaseval.py"),
        EVAL_CMD,
        "--pred", sample_data_dict[(PLASEVAL,binning,classification,merged_status)],
        "--gt", sample_data_dict[(PLASEVAL,GT,classification,UNMERGED)],
        "--out_file", sample_data_dict[(PLASEVAL,binning,classification,merged_status,EVAL_OUT)],
        "--min_len", str(args.min_len)
    ]
    in_files = [
        sample_data_dict[(PLASEVAL,GT,classification,UNMERGED)],
        sample_data_dict[(PLASEVAL,binning,classification,merged_status)]
    ]
    out_file = sample_data_dict[(PLASEVAL,binning,classification,merged_status,EVAL_OUT)]
    return plaseval_cmd,in_files,out_file

def _run_plaseval_eval(args):
    """ Run PlasEval in eval mode on a single sample for a combination (binning,classification,merged_status)
    Input:
    - args: (argparse object) argument for the plaseval command
    Output: None
    """
    # Reading data for the sample to process
    sample_data_dict = _read_samples_data(
        args.data_file, [args.sample_idx], [], args.output_dir, rerun_plaseval=args.rerun
    )[args.sample_idx]
    # Skipping if rerun and not eval or error in input file   
    if args.rerun and _read_alpha(sample_data_dict, args) not in [INPUT_FILE, EVAL_CMD]:
        return
    # Running PlasEval
    plaseval_cmd,in_files,out_file = _create_plaseval_eval_command(sample_data_dict, args)
    _check_files(in_files, in_msg="Running PlasEval -")
    try:
        plaseval_cmd_str = " ".join(plaseval_cmd)
        print(f"LOG: Running PlasEval - [{plaseval_cmd_str}]")
        result = subprocess.run(plaseval_cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Running PlasEval - [{plaseval_cmd_str}] failed with return code {e.returncode}")
        print(f"Error output: {e.stderr}")
        sys.exit(1)
    _check_files([out_file], in_msg="Running PlasEval -")

def _create_plaseval_comp_command(sample_data_dict, args):
    """ Create the command to run PlasEval in comp mode
    Input:
    - sample_data_dict: dicionary generated by _read_samples_data
    - args: (argparse object) argument for a command
    Output:
    - list(str),list(str),list(str):
    command
    path to input files (ground truth bins, predicted bins)
    path to output files (PlasEval comp scores file, PlasEval comp log file)
    """
    binning,classification = _read_binning_classification(sample_data_dict, args)
    merged_status = _read_merged_status(sample_data_dict, args)    
    plaseval_cmd = [
        f"python{args.python_version}",
        os.path.join(args.plaseval_path, "plaseval.py"),
        COMP_CMD,
        "--l", sample_data_dict[(PLASEVAL,binning,classification,merged_status)],
        "--r", sample_data_dict[(PLASEVAL,GT,classification,UNMERGED)],
        "--out_file", sample_data_dict[(PLASEVAL,binning,classification,merged_status,COMP_OUT,args.alpha)],
        "--log_file", sample_data_dict[(PLASEVAL,binning,classification,merged_status,COMP_LOG,args.alpha)],
        "--p", str(args.alpha),
        "--min_len", str(args.min_len),
        "--max_calls", str(args.max_calls)
    ]
    in_files = [
        sample_data_dict[(PLASEVAL,GT,classification,UNMERGED)],
        sample_data_dict[(PLASEVAL,binning,classification,merged_status)]
    ]
    out_files = [
        sample_data_dict[(PLASEVAL,binning,classification,merged_status,COMP_OUT,args.alpha)],
        sample_data_dict[(PLASEVAL,binning,classification,merged_status,COMP_LOG,args.alpha)]
    ]
    return plaseval_cmd,in_files,out_files

def _run_plaseval_comp(args):
    """ Run PlasEval in comp mode on a single sample for a combination (binning,classification,merged_status)
    Input:
    - args: (argparse object) argument for the plaseval command
    Output: None
    """
    # Reading data for the sample to process
    alpha = str(args.alpha)
    sample_data_dict = _read_samples_data(
        args.data_file, [args.sample_idx], [alpha], args.output_dir, rerun_plaseval=args.rerun
    )[args.sample_idx]
    # Skipping if rerun and not comp with same alpha
    if args.rerun and _read_alpha(sample_data_dict, args) not in [INPUT_FILE,  alpha]:
        return
    # Running PlasEval
    plaseval_cmd,in_files,out_files = _create_plaseval_comp_command(sample_data_dict, args)
    _check_files(in_files, in_msg="Running PlasEval -")
    try:
        plaseval_cmd_str = " ".join(plaseval_cmd)
        print(f"LOG: Running PlasEval - [{plaseval_cmd_str}]")
        result = subprocess.run(plaseval_cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Running PlasEval - [{plaseval_cmd_str}] failed with return code {e.returncode}")
        print(f"Error output: {e.stderr}")
        sys.exit(1)
    _check_files(out_files, in_msg="Running PlasEval -")

def run_plaseval(args):
    """ Run PlasEval in comp or eval mode on a single sample for a combination (binning,classification,merged_status)
    Input:
    - args: (argparse object) argument for the plaseval command
    Output: None
    """
    if args.plaseval_mode == EVAL_CMD:
        _run_plaseval_eval(args)
    elif args.plaseval_mode == COMP_CMD:
        _run_plaseval_comp(args)

def _check_plaseval_input_files(sample_data_dict, binning, classification, merged_status):
    """ Check if PlasEval input files are present and not empty
    Input: 
    - sample_data_dict: dicionary generated by _read_samples_data
    - binning: (str in BINNING) binning method
    - classification: (str in CLASSIFICATION) classification method
    - merged_status: (str in MERGED_STATUS) meged status of experiment
    Output:
    - bool
    """
    files_to_check = [
        sample_data_dict[GFA],
        sample_data_dict[(binning,classification)],
        sample_data_dict[(PLASMERGE,binning,classification,merged_status)],
        sample_data_dict[(PLASEVAL,binning,classification,merged_status)],
        sample_data_dict[(PLASEVAL,GT,classification,UNMERGED)]
    ]
    input_correct = _check_files(
        files_to_check,
        in_msg=_prefix(sample_data_dict, binning, classification),
        exit_if_pbm=False
    )
    return input_correct

def _check_plaseval_output_files(sample_data_dict, binning, classification, merged_status, alpha):
    """ Check if PlasEval output files are present and not empty
    Input: 
    - sample_data_dict: dicionary generated by _read_samples_data
    - binning: (str in BINNING) binning method
    - classification: (str in CLASSIFICATION) classification method
    - merged_status: (str in MERGED_STATUS) meged status of experiment
    - alpha: (str) EVAL_CMD (eval mode) or alpha value (comp mode)
    Output:
    - bool
    """
    if alpha == EVAL_CMD:
        files_to_check = [
            sample_data_dict[(PLASEVAL,binning,classification,merged_status,EVAL_OUT)]
        ]
    else:
        files_to_check = [
            sample_data_dict[(PLASEVAL,binning,classification,merged_status,COMP_OUT,float(alpha))],
            sample_data_dict[(PLASEVAL,binning,classification,merged_status,COMP_LOG,float(alpha))]
        ]
    output_correct = _check_files(
        files_to_check,
        in_msg=_prefix(sample_data_dict, binning, classification),
        exit_if_pbm=False
    )
    return output_correct

def _write_plaseval_check_output_file(args, failed_experiments):
    """ Write te CSV file containing failed PlasEval experiments
    Input:
    - args: (argparse object) argument for the plaseval command
    - failed_experiments: list((int,str,str,str,str))
    sample index,binning method, classification method, meged_status, alpha
    where alpha s either the PlasEval comp mode alpha value, or INPUT_FILE or EVAL_CMD
    Output: None
    creates file args.output_file
    """
    with open(args.data_file) as in_file, open(args.output_file,"w") as out_file:
        in_lines = in_file.readlines()
        out_file.write(f"{in_lines[0].rstrip()},binning,classification,merged,alpha")
        for (sample_idx,binning,classification,merged,alpha) in failed_experiments:
            out_file.write(f"\n{in_lines[sample_idx].rstrip()},{binning},{classification},{merged},{alpha}")
    
def _check_plaseval_eval(args):
    """ Check PlasEval in eval mode input/output on a set of samples for all combinations (binning,classification,merged_status)
    Input:
    - args: (argparse object) argument for the CHECK_PLASMERGE command
    Output: None
    Creates a CSV file with all failed experiments, recording the combination (binning,classification,merged_status,alpha)
    where alpha is INPUT_FILE if an input file is missing, EVAL_CMD if the eval mode failed
    """
    samples_id_range = range(1,args.nb_samples+1)
    all_samples_data_dict = _read_samples_data(
        args.data_file, samples_id_range, args.alpha.split(","), args.output_dir
    )
    failed_experiments = []
    for (sample_idx,binning,classification,merged_status) in product(
            samples_id_range,
            args.binning.split(","),
            args.classification.split(","),
            args.merged_status.split(",")
    ):
        sample_data_dict = all_samples_data_dict[sample_idx]
        # Checking PlasEval input files
        input_correct = _check_plaseval_input_files(
            sample_data_dict, binning, classification, merged_status
        )
        if not input_correct:
            failed_experiments.append(
                (sample_idx,binning,classification,merged_status,INPUT_FILE)
            )        
        # Checking PlasEval eval output files
        eval_correct = _check_plaseval_output_files(
            sample_data_dict, binning, classification, merged_status, EVAL_CMD
        )       
        if input_correct and not eval_correct:
            failed_experiments.append(
                (sample_idx,binning,classification,merged_status,EVAL_CMD)
            )
    # Writing output file
    _write_plaseval_check_output_file(args, failed_experiments)

def _check_plaseval_comp(args):
    """ Check PlasEval input/output on a set of samples for all combinations (binning,classification,merged_status)
    Input:
    - args: (argparse object) argument for the CHECK_PLASMERGE command
    Output: None
    Creates a CSV file with all failed experiments, recording the combination (binning,classification,merged_status,alpha)
    where alpha is the alpha value for comp mode that led to a failed experiment
    """
    samples_id_range = range(1,args.nb_samples+1)
    all_samples_data_dict = _read_samples_data(
        args.data_file, samples_id_range, args.alpha.split(","), args.output_dir
    )
    failed_experiments = []
    for (sample_idx,binning,classification,merged_status) in product(
            samples_id_range,
            args.binning.split(","),
            args.classification.split(","),
            args.merged_status.split(",")
    ):
        sample_data_dict = all_samples_data_dict[sample_idx]
         # Checking PlasEval input files
        input_correct = _check_plaseval_input_files(
            sample_data_dict, binning, classification, merged_status
        )
        if not input_correct:
            failed_experiments.append(
                (sample_idx,binning,classification,merged_status,INPUT_FILE)
            )        
        # Checking PlasEval comp output files
        for alpha in args.alpha.split(","):
            comp_correct = _check_plaseval_output_files(
                sample_data_dict, binning, classification, merged_status, alpha
            )
            if input_correct and not comp_correct:
                failed_experiments.append(
                    (sample_idx,binning,classification,merged_status,alpha)
                )
    # Writing output file
    _write_plaseval_check_output_file(args, failed_experiments)

def check_plaseval(args):
    """ Check PlasEval in comp or eval mode on a set of samples
    Input:
    - args: (argparse object) argument for the plaseval command
    Output: None
    """
    if args.plaseval_mode == EVAL_CMD:
        _check_plaseval_eval(args)
    elif args.plaseval_mode == COMP_CMD:
        _check_plaseval_comp(args)

def convert_to_plaseval(args):
    """ Convert bins to PlasEval format
    Input:
    - args: (argparse object) argument for the plaseval command
    Output: None
    """
    # Reading data for the sample to process
    sample_data_dict = _read_samples_data(
        args.data_file, [args.sample_idx], [alpha], args.output_dir
    )[args.sample_idx]
    # Converting bins into PlasEval format discarding repeated cotigs within a bin
    convert_bins_to_plaseval(sample_data_dict, args)

""" Main function """

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="run_utils",
        description="Running PlasMege and PlasEval"
    )
    subparsers = parser.add_subparsers(dest="command")

    parser_run_plasmerge = subparsers.add_parser(PLASMERGE, help="Running PlasMerge")
    parser_run_plasmerge.add_argument("-d", "--data_file", help="Samples CSV file")
    parser_run_plasmerge.add_argument("-i", "--sample_idx", type=int, help="Index of sample to process")
    parser_run_plasmerge.add_argument("-b", "--binning", default=None, help="Binning method to consider")
    parser_run_plasmerge.add_argument("-c", "--classification", default=None, help="Classification method to consider")
    parser_run_plasmerge.add_argument("-p", "--plasmerge_path", help="Path to PlasMerge scripts")
    parser_run_plasmerge.add_argument("-gc", "--gc_bins_file", default="gc.txt", help="Path to GC bins file")    
    parser_run_plasmerge.add_argument("-o", "--output_dir", help="Directory where all results are written")
    parser_run_plasmerge.add_argument("-v", "--python_version", default="3.9", help="Python vesion")
    parser_run_plasmerge.add_argument("--rerun", action="store_true", default=False, help="Re-running samples")

    CHECK_PLASMERGE = f"check_{PLASMERGE}"
    parser_check_plasmerge = subparsers.add_parser(CHECK_PLASMERGE, help="Checking PlasMerge")
    parser_check_plasmerge.add_argument("-d", "--data_file", help="Samples CSV file")
    parser_check_plasmerge.add_argument("-n", "--nb_samples", type=int, help="Number of sample to check")
    parser_check_plasmerge.add_argument("-b", "--binning", default=None, help="Binning methods to consider, comma-separated")
    parser_check_plasmerge.add_argument("-c", "--classification", default=None, help="Classifications method to consider, comma-separated")
    parser_check_plasmerge.add_argument("-od", "--output_dir", help="Directory where all results are written")
    parser_check_plasmerge.add_argument("-of", "--output_file", help="File where to write samples with errors")

    parser_run_plaseval = subparsers.add_parser(PLASEVAL, help="Running PlasEval")
    parser_run_plaseval.add_argument("-d", "--data_file", help="Samples CSV file")
    parser_run_plaseval.add_argument("-i", "--sample_idx", type=int, help="Index of sample to process")
    parser_run_plaseval.add_argument("-b", "--binning", default=None, help="Binning method to consider")
    parser_run_plaseval.add_argument("-c", "--classification", default=None, help="Classification method to consider")
    parser_run_plaseval.add_argument("-pm", "--plasmerge_path", help="Path to PlasMerge scripts")
    parser_run_plaseval.add_argument("-pe", "--plaseval_path", help="Path to PlasEval scripts")
    parser_run_plaseval.add_argument("-m", "--plaseval_mode", default="eval", help="PlasEval mode (eval/comp)")
    parser_run_plaseval.add_argument("-bm", "--merged_status", default=UNMERGED, help="Merged/unmerged bins")
    parser_run_plaseval.add_argument("-a", "--alpha", default=ALPHA, type=float, help="PlasEval alpha parameter")
    parser_run_plaseval.add_argument("-ml", "--min_len", default=MIN_LEN, type=int, help="PlasEval min_len parameter")
    parser_run_plaseval.add_argument("-mc", "--max_calls", default=MAX_CALLS, type=int, help="PlasEval max_calls parameter")    
    parser_run_plaseval.add_argument("-o", "--output_dir", help="Directory where all results are written")
    parser_run_plaseval.add_argument("-v", "--python_version", default="3.9", help="Python vesion")
    parser_run_plaseval.add_argument("--rerun", action="store_true", default=False, help="Re-running samples")    

    CHECK_PLASEVAL = f"check_{PLASEVAL}"
    parser_check_plaseval = subparsers.add_parser(CHECK_PLASEVAL, help="Checking PlasMerge")
    parser_check_plaseval.add_argument("-d", "--data_file", help="Samples CSV file")
    parser_check_plaseval.add_argument("-n", "--nb_samples", type=int, help="Number of sample to check")
    parser_check_plaseval.add_argument("-b", "--binning", default=None, help="Binning methods to consider, comma-separated")
    parser_check_plaseval.add_argument("-c", "--classification", default=None, help="Classifications method to consider, comma-separated")
    parser_check_plaseval.add_argument("-m", "--plaseval_mode", default="eval", help="PlasEval mode (eval/comp)")
    parser_check_plaseval.add_argument("-bm", "--merged_status", default=UNMERGED, help="Merged and/or unmerged bins, comma-separated")
    parser_check_plaseval.add_argument("-a", "--alpha", default="", type=str, help="Alpha values, comma-separated")
    parser_check_plaseval.add_argument("-ml", "--min_len", default=MIN_LEN, type=int, help="PlasEval min_len parameter")
    parser_check_plaseval.add_argument("-mc", "--max_calls", default=MAX_CALLS, type=int, help="PlasEval max_calls parameter")        
    parser_check_plaseval.add_argument("-od", "--output_dir", help="Directory where all results are written")
    parser_check_plaseval.add_argument("-of", "--output_file", help="File where to write samples with errors")

    TO_PLASEVAL = f"convert_to_{PLASEVAL}"
    parser_to_plaseval = subparsers.add_parser(TO_PLASEVAL, help="Checking PlasMerge")
    parser_to_plaseval.add_argument("-d", "--data_file", help="Samples CSV file")
    parser_to_plaseval.add_argument("-i", "--sample_idx", type=int, help="Index of sample to process")
    parser_to_plaseval.add_argument("-b", "--binning", default=None, help="Binning methods to consider, comma-separated")
    parser_to_plaseval.add_argument("-c", "--classification", default=None, help="Classifications method to consider, comma-separated")
    parser_to_plaseval.add_argument("-bm", "--merged_status", default=UNMERGED, help="Merged and/or unmerged bins, comma-separated")
    parser_to_plaseval.add_argument("-pm", "--plasmerge_path", help="Path to PlasMerge scripts")    
    parser_to_plaseval.add_argument("-o", "--output_dir", help="Directory where all results are written")
    parser_to_plaseval.add_argument("-v", "--python_version", default="3.9", help="Python vesion")    

    args = parser.parse_args()

    if args.command == PLASMERGE:
        run_plasmerge(args)

    elif args.command == CHECK_PLASMERGE:
        check_plasmerge(args)

    elif args.command == PLASEVAL:
        run_plaseval(args)

    elif args.command == CHECK_PLASEVAL:
        check_plaseval(args)

    elif args.command == TO_PLASEVAL:
        convert_to_plaseval(args)
