#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --mem=8G
#SBATCH --account=def-chauvec
#SBATCH --job-name=plasmerge_pbf
#SBATCH --array=2-500
#SBATCH --output=log/pbf/plasmerge_pbf_%A_%a.out
#SBATCH --error=log/pbf/plasmerge_pbf_%A_%a.err

source /home/chauvec/projects/ctb-chauvec/PLASMIDS/tools/env_plasbinflow/bin/activate
module load StdEnv/2020 gurobi/9.1.2

# Data and results directories and files
HOME_DIR=/scratch/chauvec/PLASMERGE/PlasMerge/
BIN_DIR=/${HOME_DIR}/src/
EXP_DIR=${HOME_DIR}/exp_20250802/
INPUT_DIR=${EXP_DIR}/input/
OUTPUT_DIR=${EXP_DIR}/output/
DATA_FILE=${EXP_DIR}/plasmids_benchmarking_2025-08-02_data.filtered.randomized.csv
GC_BINS_FILE=${EXP_DIR}/gc.txt

# Sample and input files
# Sample and input files
SAMPLE_DATA=$(sed -n "${SLURM_ARRAY_TASK_ID}p" ${DATA_FILE})
SAMPLE_ID=$(echo ${SAMPLE_DATA} | cut -f 1 -d ",")
ASSEMBLER=$(echo ${SAMPLE_DATA} | cut -f 2 -d ",")
EXP_ID=${SAMPLE_ID}_${ASSEMBLER}
GFA_FILE=$(echo ${SAMPLE_DATA} | cut -f 3 -d ",")
PLASCLASS_FILE=$(echo ${SAMPLE_DATA} | cut -f 5 -d ",")
PLASGRAPH_FILE=$(echo ${SAMPLE_DATA} | cut -f 6 -d ",")
MLPLASMIDS_FILE=$(echo ${SAMPLE_DATA} | cut -f 7 -d ",")
RFPLASMID_FILE=$(echo ${SAMPLE_DATA} | cut -f 8 -d ",")

# Sample specific directories
logger -s  "# 0. " ${EXP_ID} " creating directories"
SAMPLE_INPUT_DIR=${INPUT_DIR}/${EXP_ID}
SAMPLE_OUTPUT_DIR=${OUTPUT_DIR}/${EXP_ID}

# File suffixes
RFPLASMID="rfplasmid"
PLASCLASS="plasclass"
PLASGRAPH="plasgraph2"
MLPLASMIDS="mlplasmids"
BINNING="plasbinflow"
PM="plasmerge"
BINNING_RFPLASMID=${BINNING}_${RFPLASMID}
BINNING_PLASCLASS=${BINNING}_${PLASCLASS}
BINNING_PLASGRAPH=${BINNING}_${PLASGRAPH}
BINNING_MLPLASMIDS=${BINNING}_${MLPLASMIDS}

# Converted input file names
INPUT_BINNING_RFPLASMID_FILE=${SAMPLE_INPUT_DIR}/${EXP_ID}_${BINNING_RFPLASMID}.tsv
INPUT_BINNING_PLASCLASS_FILE=${SAMPLE_INPUT_DIR}/${EXP_ID}_${BINNING_PLASCLASS}.tsv
INPUT_BINNING_PLASGRAPH_FILE=${SAMPLE_INPUT_DIR}/${EXP_ID}_${BINNING_PLASGRAPH}.tsv
INPUT_BINNING_MLPLASMIDS_FILE=${SAMPLE_INPUT_DIR}/${EXP_ID}_${BINNING_MLPLASMIDS}.tsv

# PlasMerge output file prefixes
OUTPUT_BINNING_RFPLASMID_FILE=${EXP_ID}_${BINNING_RFPLASMID}
OUTPUT_BINNING_PLASCLASS_FILE=${EXP_ID}_${BINNING_PLASCLASS}
OUTPUT_BINNING_PLASGRAPH_FILE=${EXP_ID}_${BINNING_PLASGRAPH}
OUTPUT_BINNING_MLPLASMIDS_FILE=${EXP_ID}_${BINNING_MLPLASMIDS}
# PlasMerge output suffixes
OUTPUT_BINS_SCORES=scores.tsv
OUTPUT_MERGED_BINS=merged_bins.tsv

# Running PlasMerge
logger -s  "#" ${EXP_ID} " running " ${PM} " on " ${BINNING}
PM_METHOD="pbf"

METHOD=${BINNING_RFPLASMID}
logger -s  "## Merging " ${METHOD} "plasmid bins"
run_plasmerge.sh \
    ${BIN_DIR} ${SAMPLE_ID} ${ASSEMBLER} ${PM_METHOD} \
    ${GFA_FILE} ${RFPLASMID_FILE} ${INPUT_BINNING_RFPLASMID_FILE} ${GC_BINS_FILE} \
    ${SAMPLE_OUTPUT_DIR}/${EXP_ID}_${METHOD} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_RFPLASMID_FILE}_${OUTPUT_BINS_SCORES} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_RFPLASMID_FILE}_${OUTPUT_MERGED_BINS}

METHOD=${BINNING_PLASCLASS}
logger -s  "## Merging " ${METHOD} "plasmid bins"
run_plasmerge.sh \
    ${BIN_DIR} ${SAMPLE_ID} ${ASSEMBLER} ${PM_METHOD} \
    ${GFA_FILE} ${PLASCLASS_FILE} ${INPUT_BINNING_PLASCLASS_FILE} ${GC_BINS_FILE} \
    ${SAMPLE_OUTPUT_DIR}/${EXP_ID}_${METHOD} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_PLASCLASS_FILE}_${OUTPUT_BINS_SCORES} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_PLASCLASS_FILE}_${OUTPUT_MERGED_BINS}

METHOD=${BINNING_PLASGRAPH}
logger -s  "## Merging " ${METHOD} "plasmid bins"
run_plasmerge.sh \
    ${BIN_DIR} ${SAMPLE_ID} ${ASSEMBLER} ${PM_METHOD} \
    ${GFA_FILE} ${PLASGRAPH_FILE} ${INPUT_BINNING_PLASGRAPH_FILE} ${GC_BINS_FILE} \
    ${SAMPLE_OUTPUT_DIR}/${EXP_ID}_${METHOD} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_PLASGRAPH_FILE}_${OUTPUT_BINS_SCORES} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_PLASGRAPH_FILE}_${OUTPUT_MERGED_BINS}

METHOD=${BINNING_MLPLASMIDS}
logger -s  "## Merging " ${METHOD} "plasmid bins"
run_plasmerge.sh \
    ${BIN_DIR} ${SAMPLE_ID} ${ASSEMBLER} ${PM_METHOD} \
    ${GFA_FILE} ${MLPLASMIDS_FILE} ${INPUT_BINNING_MLPLASMIDS_FILE} ${GC_BINS_FILE} \
    ${SAMPLE_OUTPUT_DIR}/${EXP_ID}_${METHOD} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_MLPLASMIDS_FILE}_${OUTPUT_BINS_SCORES} \
    ${SAMPLE_OUTPUT_DIR}/${OUTPUT_BINNING_MLPLASMIDS_FILE}_${OUTPUT_MERGED_BINS}
